-- Schema for the runtime sidecar SQLite ledger

CREATE TABLE IF NOT EXISTS sessions (
  session_id TEXT PRIMARY KEY,
  parent_session_id TEXT,
  platform TEXT,
  profile TEXT,
  topic_key TEXT,
  started_at TEXT DEFAULT (datetime('now')),
  ended_at TEXT,
  compacted_from TEXT
);

CREATE TABLE IF NOT EXISTS route_decisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT,
  turn_id INTEGER,
  ctrl_route TEXT,
  specialists_json TEXT,
  confidence_json TEXT,
  audit_level TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS tool_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT,
  turn_id INTEGER,
  tool_name TEXT,
  args_json TEXT,
  result_ref TEXT,
  ok INTEGER,
  latency_ms INTEGER,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT,
  kind TEXT,
  content TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS compact_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  compacted_at TEXT DEFAULT (datetime('now')),
  turn_count_before INTEGER,
  tool_events_before INTEGER,
  trim_events_before INTEGER,
  summary_hint TEXT,
  trigger_source TEXT
);

-- Append-only raw tool event log — authoritative source of truth.
-- recap / DEV LOG must never replace this table as audit evidence.
CREATE TABLE IF NOT EXISTS raw_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  turn_id INTEGER,
  tool_name TEXT,
  args_json TEXT,
  result_snippet TEXT,   -- first 500 chars of raw output
  duration_ms INTEGER,
  error TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- Structured session recap generated by CTRL / Layer 2 Summarize.
-- authoritative = 0 always: recap is lossy compression, not fact source.
CREATE TABLE IF NOT EXISTS session_recaps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  source_turn_start INTEGER,
  source_turn_end INTEGER,
  trigger TEXT,          -- 'layer2' | 'pre_compaction' | 'handoff' | 'manual'
  objective TEXT,
  confirmed_facts_json TEXT,
  actions_taken_json TEXT,
  files_touched_json TEXT,
  open_issues_json TEXT,
  next_steps_json TEXT,
  uncertainty_json TEXT,
  failed_attempts_json TEXT,
  authoritative INTEGER NOT NULL DEFAULT 0  -- always 0; recap is never fact source
);